### PR TITLE
fixed wrong compilation flag in retroshare-service

### PR DESCRIPTION
**Pull request by csoler**

### CODE REVIEW

**Comment by csoler** [comment]
I'm very surprised that this flag wasn't set.  It's probably a mistake. Is it possible to generate an updated package for retroshare-service once this is merged?

**Comment by G10h4ck** [comment]
Seems strange indeed, maybe it failed on some debian based distribution so I disabled it at some point... don't remember now? Let's see what happen changing it first in retroshare-service-unstable, and if everything is fine then we backport it to 0.6.7, could you move the change to the unstable version?

**Comment by ann4belle** [comment]
~~Have not personally tested, but this should resolve #8~~ Edit: No it won't, at least not entirely. PKGBUILD, retroshare-service.spec, and appimage.yml all need to be fixed as well, or the only package that will be fixed would be the Debian version (at least, from my understanding - not familiar with OBS).

**Comment by G10h4ck** [comment]
> ~Have not personally tested, but this should resolve #8~ Edit: No it won't, at least not entirely. PKGBUILD, retroshare-service.spec, and appimage.yml all need to be fixed as well, or the only package that will be fixed would be the Debian version (at least, from my understanding - not familiar with OBS).

all the debian based, but let's see if it builds fine or if something breaks

**Comment by G10h4ck** [comment]
I have just uploaded to OBS the updated tarball for retroshare-service-unstable, let's see if everything goes fine https://build.opensuse.org/package/show/network:retroshare/retroshare-service-unstable

**Comment by G10h4ck** [comment]
@csoler @ann4belle sadly it fails to build with webui enabled, should we revert this? It or do you have a plan to work into fixing this soon ?

**Comment by csoler** [comment]
well, what is the compilation problem? Maybe it's easy to fix. On most systems retroshare-service compiles fine with rs_webui.

**Comment by G10h4ck** [comment]
@csoler I have looked at it briefly but didn't spotted any obvious error message, you can look at the build log for each debian based distro to investigate the error here https://build.opensuse.org/package/show/network:retroshare/retroshare-service-unstable

**Comment by csoler** [comment]
Apparently it fails because of this:

[   66s] make[1]: *** No rule to make target 'retroshare_gui-make_first', needed by 'rs_webui-make_first'.  Stop.

It seems that retroshare_gui is required (which does not make sense) and it's not compiled since no_retroshare_gui is among the flags in the qmake command. It seems also that cmake is involved somehow in the build process (looking at the log) which doesn't really make sense here.

**Comment by G10h4ck** [comment]
cmake is used by some library we depends on like restbed, but i don't think it have anithing to do with the error. There should be a way to tell qmake that rs_webui doesn't depends on retroshare_gui

**Comment by G10h4ck** [comment]
let's revert this until we find out, as more changes to qmake files are needed for sure

**Pull request merged**
